#ifndef VERSION_H
#define VERSION_H

#define ROVERCORE_FIRMWARE_VERSION_MAJOR 0u
#define ROVERCORE_FIRMWARE_VERSION_MINOR 1u
#define ROVERCORE_FIRMWARE_VERSION_PATCH 0u

#define ROVERCORE_FIRMWARE_VERSION "0.1.0"
#define ROVERCORE_FIRMWARE_NAME "ROVERCORE"

#endif
